# Generated by Django 4.2.1 on 2023-05-30 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0003_order_customer_name_alter_order_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer_name',
            new_name='customer_email',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
    ]
