# Generated by Django 4.2.1 on 2023-05-31 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0005_order_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
