# Generated by Django 4.2.7 on 2023-11-18 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0008_alter_product_name_alter_productimage_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='image',
        ),
    ]
