# Generated by Django 4.2.7 on 2023-11-18 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0009_remove_productimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='image',
            field=models.ImageField(default='', upload_to='product_images/'),
            preserve_default=False,
        ),
    ]
