# Generated by Django 4.2.7 on 2023-11-18 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0010_productimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='', upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
