# Generated by Django 4.2.7 on 2023-11-18 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0011_product_image_alter_product_name_delete_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
