# Generated by Django 4.2.7 on 2023-11-18 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0013_order_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer_email',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_name',
        ),
    ]
