# Generated by Django 4.2.7 on 2023-11-18 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0014_remove_order_customer_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_email',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='customer_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
