# Generated by Django 4.2.7 on 2023-11-18 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0015_order_customer_email_order_customer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
    ]
